services:
  db:
    image: postgres
    container_name: django_pim_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    container_name: django_pim_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "16041:8000"
    env_file:
      - .env
    depends_on:
      - db
